### PR TITLE
expose storage as public api & use it as global variable

### PR DESCRIPTION
**Pull request by Salimlou**
Hi @pleerock 

Two main changes in this pull request: 

- like routing controllers, global storage is now part of global variable and can be retrieved from getDefaultMetadataStorage() in storage.ts
- Export MetadataStorage in public api so we can use it.

### CODE REVIEW

**Comment by Salimlou** [comment]
The build is failing on pre 0.12 node version.

https://travis-ci.org/pleerock/class-transformer/jobs/248825807#L376

any advise @pleerock ?

**Comment by cojack** [comment]
Pollute the global space isn't good practice, what's your reason to do that?

**Comment by cojack** [comment]
@Salimlou are you still interested in this?

**Comment by Salimlou** [comment]
Hey @cojack,

Not really, you can close it.

Thks.

**Comment by Salimlou** [comment]
Hey @cojack,

Not really, you can close it.

Thks.

**Comment by Salimlou** [comment]
Hey @cojack,

Not really, you can close it.

Thks.

**Comment by cojack** [comment]
@Salimlou thanks for your time, if you have any other thoughts please, feel free to open another issue and share with us!

**Pull request closed without merging**
