### PR TITLE
Adding @TransformPlainToClass decorator

### PR DESCRIPTION
**Pull request by snirs90**
I've added a decorator to transform a plain object into a class through a decorator.

A usage example:
```
@Exclude()
class User {

    id: number;

    @Expose()
    firstName: string;

    @Expose()
    lastName: string;

    @Expose({ groups: ['user.email'] })
    email: string;

    password: string;
}

class UserController {
    
    @TransformPlainToClass(User, { groups: ['user.email'] })
    getUser() {
        const user = {};
        user.firstName = "Snir";
        user.lastName = "Segal";
        user.password = "imnosuperman";

        return user;
    }
}

const controller = new UserController();
const user = controller.getUser(); // user is instanceof User
```

### CODE REVIEW

**Comment by snirs90** [comment]
@pleerock 
Tests are fail due to -
```test/functional/circular-reference-problem.spec.ts(120,77): error TS2345: Argument of type '"isCircular"' is not assignable to parameter of type '"transform"'.```

This happens also in master - do you know why it that?

**Comment by NoNameProvided** [comment]
You can fix it this way: https://github.com/NoNameProvided/class-transformer/blob/26ae51e58f925f5c3542e2a5e06472ef465af4b4/test/functional/circular-reference-problem.spec.ts#L120

**Comment by gempain** [comment]
@NoNameProvided or just use `as any` :wink:

**Comment by cojack** [comment]
@snirs90 thanks for your work! I have accept your PR, and will be published on next version v0.1.11

Thanks guys for your time!

**Pull request merged**
