### PR TITLE
fix: #143 Use custom transform on CLASS_TO_PLAIN

### PR DESCRIPTION
**Pull request by driccio**
Here a naive fix of the issue #143.

### CODE REVIEW

**Comment by driccio** [comment]
Hello,

A new version of my pull request with all tests green.
I would be interested to get a feedback about it and know if it could be integrated in a new release.

**Comment by ofavre** [comment]
What's up with this pull request?

**Comment by MTschannett** [comment]
@driccio This looks good to me. Could you please  solve the merge conflicts.

This would cover the problems mentioned in this issues: #163, #127.

**Comment by MTschannett** [comment]
@cojack Are there any side effects that I'm not seeing?

**Comment by MTschannett** [comment]
@driccio Please use develop as the target for your PR. Thank you

**Comment by cojack** [comment]
@MTschannett I'm in! But how about docs, do we have any? What exactly it does?

**Comment by NoNameProvided** [comment]
The needs docs flag can be removed once #181 gets fixed.

**Comment by driccio** [comment]
Hello team,

I am sorry to not have ansered you, but I didn't received notifications from Github. I see now the status is fixed : very good :+1: 

Happy to see the project is alive. I am using it with a lot of pleasure, but was worried about it's future. I maybe will have new issues to open.

So congrats for your work and thanks.

**Pull request merged**
