### PR TITLE
get type of nested objects through reflect-metadata when enable `emitDecoratorMetadata`

### PR DESCRIPTION
**Pull request by s97712**
…DecoratorMetadata`

### CODE REVIEW

**Comment by MTschannett** [comment]
Thank you for your PR. Could you please add some context to this. Maybe an issue number or a short description?

**Comment by s97712** [comment]
That can automatically get type of nests object and don't need use @Type decorator when enable emitDecoratorMetadata option of typescript.

**Comment by MTschannett** [comment]
ok . sounds good . is this only nest specific? A comment mentioning that would be good.

**Comment by s97712** [comment]
Yes, may we need a new library work with `emitDecoratorMetadata`

**Comment by NoNameProvided** [comment]
Hi @s97712! 

Before this can get merged, please discuss in details what it does. 
 - provide some code examples this change fixes
 - branch needs to be update with develop
 - needs to target the develop branch

> don't need use @type decorator when enable emitDecoratorMetadata option of typescript.

Type metadata is emitted only if there is at least one decorator on the property, please keep that in mind.

**Comment by NoNameProvided** [comment]
Closing as invalid, because of no response from the author.

**Pull request closed without merging**
