### PR TITLE
Polymorphism

### PR DESCRIPTION
**Pull request by janis91**
Added the possibility to provide an array of discriminator functions in case of an array of different types.

If you have any other proposal for doing this, comment here or in the related ticket: #51

### CODE REVIEW

**Comment by NoNameProvided** [comment]
> One question: travis is complaining, but I cannot reproduce it locally 

Only Node 4 is failing with

```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

Don't care about it, it's already removed from routing-controllers, so I will remove it from here as well.

**Comment by janis91** [comment]
@NoNameProvided any thoughts on this already?

**Comment by janis91** [comment]
It has been quite some time since I updated. Is there anything left why this does not get integrated?
@NoNameProvided

**Comment by NoNameProvided** [comment]
Hi @janis91 

It's because I have 100+ Github issue, and short on time. I am also not fully engaged with class-transformer yet, as I want to kick class-validator to 1.0 first then working on class-transformer.

We can ask a review from @pleerock, if he finds it ok, we can merge.

**Comment by NoNameProvided** [comment]
Will try to go through the PRs during the easter. :) No promises tho.

**Comment by janis91** [comment]
@NoNameProvided Please do not get me wrong. I just wondered if I have to to do something else or if it's just because you are busy (no problem with that, I have that problem for my projects as well). Still I would appreciate it if you have the time during easter :-)

**Comment by janis91** [comment]
@mustafaekim You're right, the PR covers arrays only. But this is because it is already possible to give a function that determines the type based on the given TypeOptions for single properties. The only thing that was missing, was the possibility to differentiate objects inside of an array.

But in order to be able to provide multiple discriminator functions also for a single property, I could try to add the logic for this case as well.

**Comment by mustafaekim** [comment]
OK thanks. I would prefer adding a property (whos key can be set) to the json (discriminator property) indicating the class type.

**Comment by janis91** [comment]
@mustafaekim could you provide an example, I think I am not understanding what you mean.

**Comment by mustafaekim** [comment]
That's how you discover the constructor function:

```
export abstract class Photo {
    id: number;
    filename: string;
}

export class Landscape extends Photo {
   panorama: boolean;
}

function isLandscape(value: any): Function | false {
    return value.panorama !== undefined ? Landscape : false;
}

export class Album {
    id: number;
    name: string;
    @Type(() => [ isLandscape, isPortrait, isUnderWater ])
    topPhoto: Landscape | Portrait | UnderWater;
}
```

What I propose is, when transforming from class to json, it may be better to add a discriminator property (like __type) to the json so that when we transform back, we can simply check the value of the discriminator property and find the constructor. Your solution may be optional but by default a adding a discriminator property will work well for 99% of cases

That's how typedjson, Jackson (Java) work

**Comment by janis91** [comment]
@mustafaekim I tried what I think was your idea. Please check it out.

**Comment by mustafaekim** [comment]
Hi, I've read the code, it's like the way I was trying to describe.

can't the code below
```ts
topPhoto: Landscape | Portrait | UnderWater;
```
be
```ts
topPhoto: Photo;
```
?

**Comment by janis91** [comment]
@mustafaekim Well, actually the ``topPhoto`` can only be of type Photo, when the json input doesn't match the other types (because it is used as a fallback). 
But in general I would say, that you lose the support of typescript in terms of auto completion and so on, if you just type ``Photo`` (it is most likely that you will not only get a Photo, but a Landscape, Portrait or UnderWater photo and you may want to use the different properties they introduce.

**Comment by mustafaekim** [comment]
I didnt know that in Typescript if you use the type Photo, you do not get support for tooling. That's interesting. That is not how it works in tooling for other languages. Anyway thank you for clarification.

Is there any schedule when this feature will be merged into the core of the library? (@NoNameProvided )

**Comment by cojack** [comment]
Hi
@janis91 thanks for your work, I have accept your PR and will be published into next version as 0.1.11

Thanks for your time :heart_eyes: 
Please feel free to contribute for another PR!

**Comment by lucaswxp** [comment]
Hello guys.

Was this solved? Is it already stable?

**Comment by agersea** [comment]
+1 any ETA on this?

**Pull request merged**
