### PR TITLE
Add new decorator for casting to Boolean

### PR DESCRIPTION
**Pull request by Goodluckhf**

### CODE REVIEW

**Comment by NoNameProvided** [comment]
My opinion about this PR is the same as I wrote in #334. This is out of scope for _class-transformer_. In JSON we have a well-defined way of using boolean values: `{ propA: true, propB: false }`. 

If this feature is crucial for someone, this can be easily implemented with a `@Transform` decorator.

**Comment by Goodluckhf** [comment]
> My opinion about this PR is the same as I wrote in #334. This is out of scope for _class-transformer_. In JSON we have a well-defined way of using boolean values: `{ propA: true, propB: false }`.
> 
> If this feature is crucial for someone, this can be easily implemented with a `@Transform` decorator.

Yes, that's why i implemented it as a separated decorator and didn't change default usage.
I need it in transforming config from `env` variables where everything is string (https://github.com/ukitgroup/nestjs-config). So I think it will be nice idea to add some wrappers for comfortable transformation out of the box like: `@ToBoolean()` , `@ToInteger()`, `@ToNumber()` and so on...

**Comment by NoNameProvided** [comment]
>  So I think it will be a nice idea to add some wrappers for comfortable transformation out of the box like @ToBoolean() , @ToInteger(), @ToNumber() and so on...

You can achieve this currently by enabling implicit conversion. 

I understand `boolean` is a special kind as in some scenarios boolean values received as strings in the  `true` | `false` from (env variables, query params). We need to think this through, as last resort, we can add an extra flag which allows parsing of Boolean based on content but that is the last resort solution. 

However, adding extra decorators I don't think we will do it encourages an (in my opinion) invalid workflow. class-validator should be able to infer what basic type you wanted to get there and if you need to use decorators them something is not handled correctly. (Again booleans are a somewhat special case, so I am not implying anything negative regarding your approach.)

**Comment by NoNameProvided** [comment]
Closing in favor of #550.

**Pull request closed without merging**
