### PR TITLE
Fix transform of null primitive values

### PR DESCRIPTION
**Pull request by sparebytes**
This fixes a bug where null and undefined values are converted to "null" and "undefined" for properties with `@Type(() => String)`:

eg,
```
class Box {
    @Type(() => String)
    value: string | null
}

plainToClass(Box, { value: null });
// Before: { value: "null" }
// After: { value: null }
```

### CODE REVIEW

**Comment by pleerock** [comment]
Hi and thank you for your contribution. Would be great if you add tests for your changes since this functionality can be easily broken very soon by other changes without being test-covered

**Comment by sparebytes** [comment]
I added tests in the [second commit](https://github.com/typestack/class-transformer/pull/110/commits/597a98456292ce544e012e2dcb82be8243a8bfa4). These new tests will fail without the fix in the first commit.

**Comment by sparebytes** [comment]
bump

**Comment by ahmadhsalim** [comment]
I'm facing this issue. The fixes in that commit works. When would it be merged?

**Comment by cojack** [comment]
Hi,
@sparebytes thanks for you work, I accept your PR, it will be published into new version 0.1.11.

Thanks for your time :heart_eyes: 
Feel free to contribute another PR.

**Pull request merged**
