### PR TITLE
Update MetadataStorage.ts

### PR DESCRIPTION
**Pull request by tbreug**
Bugfix for "ERROR TypeError: Cannot read property 'prototype' of undefined" in decorator @Transform.

### CODE REVIEW

**Comment by gempain** [comment]
@tbreug Glad somone is giving it a go. We've been waiting for this fix for a while now.

**Comment by gempain** [comment]
@tbreug I would suggest adding a unit test that reproduces the original bug and tests that it is fixed :)

**Comment by tbreug** [comment]
I don't think we need a unit test since this simple change was just about avoiding null-pointer-exception.
I tested it locally on Angular4/Ionic - @Tranform now works fine for custom model serialization.

**Comment by gempain** [comment]
I agree with you, but this change will also fix many open issues where people had the infamous `Cannot read property ... of undefined`.

> I tested it locally on Angular4/Ionic - @Transform now works fine for custom model serialization.

Hence why we need a unit test, so that you don't have to test locally, but let CI do that for you :) I think we should have a unit test for specifically making sure this does not happen in the future :)

**Comment by tbreug** [comment]
What about test/functional/custom-transform.spec.ts?

**Comment by gempain** [comment]
For reference: #28 #63 #64 

I guess you could add a test in `test/functional/custom-transform.spec.ts` like:

```typescript
it('should not throw an error when the property is not annotated with @Type or it\' prototype is undefined', () => {
  expect(() => {
    class B {}

    class A {
      @Transform(value => value, { toClassOnly: true })
      b: B;
    }

    plainToClass(A, {} as any)
  }).not.toThrowError();
});
```

But again, it's just a personal opinion, don't take my word for it.

Don't know if this could be useful, but I saw that another user [had also implemented a fix](https://github.com/britvik/class-transformer/commit/0a1144ce787ec04b19088a621f8e905b35852875) (but never PR'd it).

**Comment by gempain** [comment]
@tbreug I know, TSLINT is a pain :wink:

**Comment by tbreug** [comment]
Unit test added - finally

**Comment by gempain** [comment]
@tbreug you got it ! Part of it was my fault as I told you to use `.not.toThrow()`. I don't know why it wasn't working. In my personal projects that's what I use. I guess `sinon` has a different API, the code I gave you was for `jasmine` :smile: 

Great work anyway, I could get all the email notifications and follow your struggle with TSLINT too :stuck_out_tongue:

**Comment by tbreug** [comment]
Thanks for your support. My linter forces me to use single quotes. I look forward now to have the pull request and the transformer working since I'd love to populate [and validate] my models by annotation only.

**Comment by vicente-valls** [comment]
can you please merge this ? :smile_cat: looking forward this fix

**Comment by tbreug** [comment]
The master branch hasn't been merged into since a year now. Who knows, when it's gonna be updated.
If you don't need the obj param in the @Transform decorator, you might look for node package "class-transformer-fixed". If you need that parameter, you could pull the branch and transpile for your own repos or npm.

**Pull request merged**
