### PR TITLE
feat: pass ClassTransformOptions to the transformFn of @Transform

### PR DESCRIPTION
**Pull request by lgregoire-yseop**
The goal of this PR is to be able to access to `ClassTransformOptions` provided by transformation methods directly inside the `transformFn` of `@Transform` decorators.

```ts
class User {
    @Expose()
    name: string;

    @Expose()
    @Transform((_0, _1, _2, options) => options.groups)
    groups: string[];
}

plainToClass(
    User,
    { name: 'Johny Cage' },
    { groups: ['user.full'] },
)

// Result
// User {
//    name: 'Johny Cage',
//    groups: ['user.full'],
// }

```

Another use-case could be:
If i want to use a transformation method (e.g. `plainToClass`) inside a `@Transform` and extend the groups, I can do:
```ts
class User {
    @Expose()
    name: string;

    @Expose()
    @Transform(
        (value, _0, _1, { groups: inheritedGroups }) => plainToClass(
            Foo, 
            value, 
            { groups: [...inheritedGroups, 'additional_group'] }
        ),
        { toClassOnly: true }
    )
    foos: Foo[];
}
```

This pull request fixes following issues:
- https://github.com/typestack/class-transformer/issues/238
- https://github.com/typestack/class-transformer/issues/208

### CODE REVIEW

**Comment by cojack** [comment]
Hmm can we trigger somehow travis to make a run once again for this MR, to check why the heck tests fail?

**Comment by lgregoire-yseop** [comment]
I force-pushed the last commit to trigger a new build.
But there is a compatibility issue between `gulp@3` and `node@12` (current `stable`): https://github.com/gulpjs/gulp/issues/2324
So it's necessary to upgrade `gulp` to v4

**Comment by lgregoire-yseop** [comment]
https://github.com/typestack/class-transformer/pull/266/files
https://github.com/typestack/class-transformer/issues/263

**Comment by stewartmcgown** [comment]
Is something blocking this PR being merged? Seems like a very useful feature. Happy to review if one is needed.

**Comment by julien-sarazin** [comment]
Hi there, I need this feature so hard. Please make class-transformer great again!

**Comment by NoNameProvided** [comment]
This is related to #330. We need to rebase this after that one is merged.

**Comment by lgregoire-yseop** [comment]
Rebase is done, fell free to comment/review :wink:

**Review by NoNameProvided — APPROVED** [review]

**Pull request merged**
