### PR TITLE
New CatchNotExposed decorator to do custom processing for extra attributes

### PR DESCRIPTION
**Pull request by melfa**
I implemented a feature to do custom processing for attributes not have @Expose decorator.
Example:
```
// plain object
{
  "name": "test",
  "extra1": 1
}

export class Test {
  @Expose()
  name: string;

  extraAttributes: object;

  // new decorator introduced
  @CatchNotExposed()
  public catchNotExposed(propertyName: string, value: any) {
    // can do any custom logic with all extra attributes
    this.extraAttributes[propertyName] = value;
  }

}

// plainToClass result
{
  "name": "test",
  "extraAttributes": {
    "extra1": 1
  }
}
```

This is suitable for allowing to automatically store extra attributes in database in JSON column, while basic attributes will go to specified columns.

If you think this feature is out of project's scope - can you please suggest how to do this in other way? I would like to use class-transformer's decorators to know which attributes is extra and which is core.

### CODE REVIEW

**Comment by MTschannett** [comment]
@melfa The goal you want to achieve with this decorator is to get all values that shouldn't be exposed and add them back to your object?

Do I understand this correctly? Why do you not expose the other properties?

**Comment by MTschannett** [comment]
@cojack  @NoNameProvided  Do you think this is in the scope of this project? I'm not entirly sure.

**Comment by cojack** [comment]
Emmm, I really don't understand purpose of it. For example, I have another problem, like not exposed properties from class are filled, and I don't know how your example could works, I have to investigate some time.

**Comment by melfa** [comment]
This is no longer important for me, i have already found another solution, please close issue :)

**Comment by melfa** [comment]
This is no longer important for me, i have already found another solution, i'm close issue :)

**Comment by melfa** [comment]
This is no longer important for me, i have already found another solution, i'm close issue :)

**Comment by MTschannett** [comment]
@melfa Thank you

**Comment by melfa** [comment]
This is no longer important for me, i have already found another solution, i'm close issue :)

**Comment by cojack** [comment]
@melfa what solution, can you share?

**Comment by melfa** [comment]
@cojack i changed API so all extra attributes become documented and fixed (moved responsibility from frontend to backend).

**Pull request closed without merging**
