### PR TITLE
fix: compatible with swc output

### LINKED ISSUE #796: feature: make class-transformer compatible with swc output
### Description

Hi. After switching from **ts-node** to [**swc**](https://github.com/swc-project/swc), I find that class-transformer cannot work properly. After some investigation, I find that t[his line](https://github.com/typestack/class-transformer/blob/f5a654a98e8bdb6316ee775d86565f3b843e3416/src/TransformOperationExecutor.ts#L295) misses a condition. The full if check should (or might) be like [this](https://github.com/Youmoo/class-transformer/blob/26be0bb0abf1aa381a47cc43bf58ddd874a38795/src/TransformOperationExecutor.ts#L295).

### Proposed solution

I have made a repostory to demonstrate the above issue:

- repo: https://github.com/Youmoo/class-transformer
- branch: swc-compatible
- command: `npm run test:swc`

If we remove the `!('value' in descriptor)`  check, the swc test will fail.

*If you think this feature is acceptable, I'm happy to make a PR. Thank you*

### PR DESCRIPTION
**Pull request by 0xDing**
## Description

Fix swc compilation compatibility. When applying the plainToClass function to a class defined with class-validator and built with swc, it returns the class with no attributes

Special thanks to @youmoo

## Checklist

- [x] the pull request title describes what this PR does (not a vague title like `Update index.md`)
- [x] the pull request targets the *default* branch of the repository (`develop`)
- [x] the code follows the established code style of the repository
  - `npm run prettier:check` passes
  - `npm run lint:check` passes
- [ ] tests are added for the changes I made (if any source code was modified)
- [ ] documentation added or updated
- [x] I have run the project locally and verified that there are no errors

### Fixes

fixes #796 
references swc-project/swc/issues/2117

### CODE REVIEW

**Comment by stewartmcgown** [comment]
Surely this is up to SWC to make behaviour more compliant with the exisiting way of doing things?

**Comment by yharaskrik** [comment]
+1 on this, it is preventing us from using swc to compile our nest apps.

Not sure if this is on the class-transformer side or swc side but I can confirm this change does fix the issue.

**Comment by tonivj5** [comment]
> Not sure if this is on the class-transformer side or swc side but I can confirm this change does fix the issue.

Using tsc works, so I think the problem is on swc side... Fixing this package could be a patch meanwhile swc gets the correct approach, but other packages could fail

**Comment by minardimedia** [comment]
There is also a similar issue when upgrading to Next js 12, they use SWC and support legacy decorators but the @Expose() and @Exclude() decorators also seem to be falling. they return undefined attributes.

**Comment by unlight** [comment]
@0xDing
Can you tell us, all unit tests of class-transformer will pass with this fix?

**Comment by leonardopliski** [comment]
@0xDing Thanks for this fix!
Do you have any plans on publishing this? This change will help a lot of codebases that would like to adopt `swc` together with `class-transformer`.

**Comment by vladshcherbin** [comment]
Holy shit, finally found what was the reason why `nestjs` and `class-transformer` didn't work, body values seemed to be undefined. Currently not possible to use with `swc`.

**Comment by tonivj5** [comment]
> > Not sure if this is on the class-transformer side or swc side but I can confirm this change does fix the issue.
> 
> Using tsc works, so I think the problem is on swc side... Fixing this package could be a patch meanwhile swc gets the correct approach, but other packages could fail

This has been fixed by swc https://github.com/swc-project/swc/pull/3459 🚀 ~Waiting for the next release~ https://github.com/swc-project/swc/releases/tag/v1.2.137 🎉

**Pull request closed without merging**
