### PR TITLE
add option to remove extraneous values

### PR DESCRIPTION
**Pull request by nimaen**
Discussed in #198

### CODE REVIEW

**Comment by nimaen** [comment]
I'm not sure if that does respect exposed names 🤔

**Comment by MTschannett** [comment]
What do you mean with it doesn't respect exposed names? Shouldn't this PR fix that?  ^^ 
Or am i misunderstanding you?

**Comment by kalani96746** [comment]
Seems like this is a good fix.  Iʻve witnessed adding something to a class occurs if you have properties on the plain object that arenʻt on the typescript class.

**Comment by nimaen** [comment]
After watching this again, I think I overthought the Expose decorator.
We're good to go.
Is this the correct way to handle this feature though ?
Should it be used as a strategy instead ?

**Comment by MTschannett** [comment]
I think we should add a short note in the readme, that we set undefined for properties, that were not present before. 
And also for the new option. After that I'm happy to merge it

**Comment by nimaen** [comment]
@MTschannett Documentation added.
Feel free to fix my sentences / examples as you see fit 😉

**Comment by MTschannett** [comment]
Merged your changes thanks again :)

**Comment by nimaen** [comment]
You're welcome, ping me if anything comes up 😉
Closes #198

**Pull request merged**
