### PR TITLE
Add doc section for ES6 collections Set and Map

### PR DESCRIPTION
**Pull request by thevtm**

### CODE REVIEW

**Comment by NoNameProvided** [comment]
Why have you closed this? Not having a review yet doesn’t mean it’s a bad PR. Or did this functionality changed ?

**Comment by thevtm** [comment]
I closed bc it's a month old and I got no feedback.

**Comment by NoNameProvided** [comment]
You should reopen. @pleerock is on holiday so no surprise that he hasn’t get the time to review this. I am sure he will when he has some time.

**Comment by davidshepherd7** [comment]
This would be useful to have merged if possible.

It might also be worth mentioning that this only (seems) to work if the member has an **explicit** type declared. i.e.

```typescript
    @Type(() => Unit)
    private _units: Map<string, Unit> = new Map<string, Unit>();
```

works fine, but

```typescript
    @Type(() => Unit)
    private _units = new Map<string, Unit>();
```

attempts to deserialize it as a `Unit` rather than a `Map<string, Unit>`. I was very confused by this and I only figured it out by exactly copying the test cases for es6 map serialization.

**Pull request merged**
