### PR TITLE
Pass in options to methods

### PR DESCRIPTION
**Pull request by lazarljubenovic**
From #208 (precisely https://github.com/typestack/class-transformer/issues/208#issuecomment-439434640, **3b**).

No breaking changes.

### CODE REVIEW

**Comment by MTschannett** [comment]
This branch can't be merged because it's out of sync. 

Btw. is some user-facing documentation needed for this?

**Comment by lazarljubenovic** [comment]
I'll rebase and add docs during the weekend.

**Comment by MTschannett** [comment]
I'll look forward to merge this ^^

**Comment by NoNameProvided** [comment]
I have commented on the linked issue. (Exposing to the `@Transform` is fine, but exposing class-validator internals to the host class is an anti-pattern and opens up a bunch of new problems. I am closing this PR as won't fix.

**Pull request closed without merging**
