### PR TITLE
Transform callback should override default transform function (fixes #72)

### LINKED ISSUE #72: question: transformations on arrays
Is it possible to perform transformations on an array field?

For example say on the wire / json i have an array of CSV strings, which i want to deserialize into an array of pairs.

Here's a sample test (added into transformer-method.spec.ts) to demonstrate further:

```
it("should allow array transformations", () => {
        class TopLevel {
            @Type(() => Child)
            @Transform((values: string[]) => values.map(value => Child.fromCsv(value)), {toClassOnly: true})
            @Transform((values: Child[]) => {
                console.log("Values:     " + JSON.stringify(values));
                console.log("1st value:  " + JSON.stringify(values[0]));
                console.log("is a Child: " + (values[0] instanceof Child));
                console.log("type:       " + (typeof values[0]));
                return values.map(value => value.toCsv());
            }, {toPlainOnly: true})
            children: ChildCollection;
        }

        class ChildCollection extends Array<Child> {

        }

        class Child {
            prop1: string;
            prop2: string;

            toCsv() {
                return [this.prop1, this.prop2].join(",");
            }

            static fromCsv(csv: string) {
                const child = new Child();
                [child.prop1, child.prop2] = csv.split(",");
                return child;
            }
        }

        const top = new TopLevel();
        top.children = [];
        top.children.push(Child.fromCsv("123,abc"));

        console.log("children:   " + JSON.stringify(top.children));
        console.log("1st child:  " + JSON.stringify(top.children[0]));
        console.log("is a Child: " + (top.children[0] instanceof Child));
        console.log("type: " + (typeof top.children[0]));

        // deserialization works without an issue
        const expectedSerialized = {children: ["123,abc"]}
        const deserialized = plainToClass(TopLevel, expectedSerialized);
        expect(deserialized).to.deep.equal(top);

        // serialization has an issue however
        const actualSerialized = classToPlain(top);
        expect(actualSerialized).to.deep.equal(expectedSerialized);
    });
```

The test fails with the following error:

```
  transformer methods decorator

children:   [{"prop1":"123","prop2":"abc"}]
1st child:  {"prop1":"123","prop2":"abc"}
is a Child: true
type: object

Values:     [{"prop1":"123","prop2":"abc"}]
1st value:  {"prop1":"123","prop2":"abc"}
is a Child: false
type:       object

    1) should allow array transformations
    ✓ should expose non configuration properties and return User instance class
    ✓ should expose non configuration properties
    ✓ should expose non configuration properties and properties with specific groups
    ✓ should expose non configuration properties with specific version


  53 passing (280ms)
  1 failing

  1) transformer methods decorator should allow array transformations:
     TypeError: value.toCsv is not a function
      at build/es5/test/functional/transformer-method.spec.js:39:71
      at Array.map (native)
      at TransformMetadata.decorators_1.Transform.toPlainOnly [as transformFn] (build/es5/test/functional/transformer-method.spec.js:39:35)
      at build/es5/src/TransformOperationExecutor.js:9:16977
      at Array.forEach (native)
      at TransformOperationExecutor.applyCustomTransformations (build/es5/src/TransformOperationExecutor.js:9:16856)
      at _loop_1 (build/es5/src/TransformOperationExecutor.js:9:13244)
      at TransformOperationExecutor.transform (build/es5/src/TransformOperationExecutor.js:9:14567)
      at ClassTransformer.classToPlain (build/es5/src/ClassTransformer.js:9:802)
      at Object.classToPlain (build/es5/src/index.js:9:1017)
```

The console.log debug statements show that when the children object is passed to the `@Transform` decorator function, it's no longer an array of Child objects (but an array of POJOs), and hence calling the Child::toCSV() method on it fails.

Is this a bug, or is there another pattern i should be using to use transformers on arrays? (Deserialization works as expected)

### PR DESCRIPTION
**Pull request by gempain**
Fixes #72 and introduces a breaking change: callbacks registered by `@Transform` will override the default transform. Previously they would receive a pre-transformed value, but this is not the case anymore. The default transform function is used unless custom transform callbacks are available.

Filtering is done after version and group checks in order to know the true number of custom transform functions that would be applied.

@pleerock do you think this is a breaking change ? I had to change a transform callback in one of the `@Transform` tests, so we could consider it a breaking change, but since we're just at version 0.1.8, I don't see a point to bump the major version. I guess a minor bump would be enough ?

Note that it is still possible to delegate transform to the default callback by throwing an error in the `@Transform` callback  😀

### CODE REVIEW

**Comment by HideDev** [comment]
@pleerock can you see PR?

**Comment by justvovus** [comment]
Hi guys,
Is the project still alive? Looks like nobody reacts on PR for months.

**Comment by 19majkel94** [comment]
Pleerock hasn't got time for this project right now, he focus all on TypeORM. But he promised that in a few months he will take care of the rest of his project. You can ping @NoNameProvided, maybe he will help wit it 😉

**Comment by NoNameProvided** [comment]
I will take a look soon.

**Comment by mcwebb** [comment]
This PR would definitely make the functionality more intuitive for me; the current implementation tripped me up just now - had to step through the code to understand what was happening.

I'd be interested to hear the original rationale for running the default transform prior to the custom transform, maybe there's a use-case that I'm not thinking of?

**Comment by cojack** [comment]
Hi guys,
@gempain thanks for your work, could you explain it a bit more by some documentation example to provide a bit more information about this behaviour and where is the breaking changes, because I can not see them to be honest.

@mcwebb any help will be useful, so if you have time to provide some docs, I will be glad.

Thanks in advance.

Regards

**Comment by NoNameProvided** [comment]
@gempain can u give us an update on this?

**Comment by gempain** [comment]
@cojack I did this PR a year ago... Looking at it today, I indeed don't see any breaking change, except that I had to slightly adapt a unit test. There isn't much to document really. The major difference with the older behavior is as follows:

In `@Transform(value => ...)`:

**Before**: `value` is pre-transformed using the default transformer, then sent to the custom transformer `value => ...`.
**After**: `value` is only sent to the custom transformer `value => ...`.

I don't know what motivated the original behavior, but it caused problems when trying to use custom transformers. In other words, when I provide a custom transformer, I expect my transformer to receive the plain javascript value, not pre-processed by any other callback - I mean, it's the point of providing a custom transformer.

**Comment by Hossein-s** [comment]
@cojack @NoNameProvided Is there any issues?

**Comment by Roms1383** [comment]
Having a look at your [comment](https://github.com/typestack/class-transformer/pull/96#issuecomment-436588818) @gempain :
> In other words, when I provide a custom transformer, I expect my transformer to receive the plain javascript value, not pre-processed by any other callback - I mean, it's the point of providing a custom transformer.
You can actually access the plain javascript object and retrieve your value from it using :
```ts
@Transform((value, plain) => ...)
```
This way you can bypass the pre-transform step.
Hope this helps 😀

**Comment by gempain** [comment]
It's almost 2021 😆

**Comment by gterras** [comment]
It's almost 2023 :laughing:

**Comment by gempain** [comment]
It's 2024.

**Pull request closed without merging**
